name: Selenium Tests

on:
  # schedule:
    # - cron: '0 */4 * * *' # Run every hour
  workflow_dispatch:

jobs:
  selenium-tests:
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, windows-2019]
        python-version: ['3.8', '3.10', '3.11']

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: |
      #     pip install selenium chromedriver_autoinstaller
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y wget unzip
      #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #     sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
  
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install chromedriver-autoinstaller
          pip install webdriver-manager

      - name: Run Selenium script
        run: python youtube_bot_stream.py

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./
